### ISSUE TITLE
Ankiweb: you uploaded the wrong add-on

### ISSUE THREAD

**Issue by ijgnd** [Arthur-Milchior/anki-template-card-type#3]
yesterday you updated [Edit card's template with python and a domain specific language](https://ankiweb.net/shared/info/1159566613).

By accident  you uploaded the source code files for multi-column note add-on to the address of the anki-template-card-type add-on.

Thanks for sharing this fascinating add-on.

**Comment by Arthur-Milchior** [comment]
Thank you for letting me know. And by the way, letting me know that at least one other person uses this add-on

**Comment by ijgnd** [comment]
Thanks for the quick fix. I must admit I'm still just experimenting with your add-on. Just experimenting because in the last weeks I spend a lot of time with supermemo instead of seriously reconsidering my anki routines.
