### ISSUE TITLE
Addon doesn't work with Ubuntu 20.04

### ISSUE THREAD

**Issue by bmihovski** [Arthur-Milchior/anki-template-card-type#4]
Hello Arthur,

Thank you for the great addon I really like it.
I am trying to use the addon with Ubuntu 20.04 where python version is 3.8
Anki app is installed via apt

Now I am having this in addon settings
`{
    "Shortcut: Clean Template note": null,
    "Shortcut: ReTemplate Card": "Ctrl+Shift+T",
    "Shortcut: ReTemplate note": "Ctrl+Alt+Shift+T",
    "Shortcut: Template Note": "Ctrl+Alt+T",
    "Shortcut: frontside": null,
    "instructions": []
}`

This is Anki debugging info:

`Anki 2.1.15 (442df9d6) Python 3.8.2 Qt 5.12.8 PyQt 5.14.1
Platform: Linux
Flags: frz=False ao=True sv=2

Add-ons:

Speed Focus Mode auto-alert auto-reveal auto-fail
Edit cards template with python and a domain specific language
Spelling Police
Rebuild All  Empty All for Anki 21
Button Colours Good Again
Adding note and changing note type become quicker
Create Filtered Deck from the Browser`

Thank you,
Boyan

**Comment by Arthur-Milchior** [comment]
Can yo please post the error message, or the reason why you think it does not work ? 
2.1.15 is not thelatest verson of anki, but I would expect the add-on to work with it nonetheless.

FYI anki comes with its own version of Python, its own virtualenv, so the version by default on your ubuntu does not matter here

**Comment by bmihovski** [comment]
There is no error message, just the addon icon is not present when a card is created or edited. All of the existing card with code snippets are visualized normally. (I have another computer with Mac and the issue is not present there)

**Comment by Arthur-Milchior** [comment]
Which add-on icon ? The only thing this add-on adds is a button in a browser's menu

**Comment by bmihovski** [comment]
Exactly the button is not present

**Comment by Arthur-Milchior** [comment]
Would you accept to install the last version from ankisrs.net ? I am surprised, but I won't take time to debug older version.
I'm really sorry that ubuntu is really outdated with anki; but I am not going to spend time debugging for older version.

**Comment by bmihovski** [comment]
Sure. I installed it but still the same. Thanks
`    
    Anki 2.1.22 (0ecc189a) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
    Platform: Linux
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2020-05-11 19:05:11
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Adding note and changing note type become quicker ['802285486', 2020-05-10T12:18, 'None', '']
    Button Colours Good Again ['2494384865', 2020-05-10T12:04, 'None', '']
    Create Filtered Deck from the Browser ['861263371', 2020-05-10T12:05, 'None', '']
    Edit cards template with python and a domain specific language ['1159566613', 2020-05-10T12:19, 'None', '']
    Rebuild All  Empty All for Anki 21 ['1810938259', 2020-05-10T12:06, 'None', '']
    Speed Focus Mode auto-alert auto-reveal auto-fail ['1046608507', 2020-05-10T12:07, 'None', '']
    Spelling Police ['1410276506', 2020-05-10T12:08, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1046608507 1159566613 1410276506 1810938259 2494384865 802285486 861263371
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    
`
![Screenshot from 2020-05-11 19-09-12](https://user-images.githubusercontent.com/4339683/81584172-13e28080-93bb-11ea-93c3-0d4f63d9bfa6.png)

**Comment by Arthur-Milchior** [comment]
I don't understand what your screenshot is supposed to show me. There has never be any button related to this add-on on the "add-card" window. Are you sure you're not looking for another add-on maybe ?

**Comment by bmihovski** [comment]
You are absolutely right.
I am really sorry it was for different addon - https://ankiweb.net/shared/info/1463041493
My bad next time will take snapshot from the installed addons before OS reinstallation.
I am closing the issue.
Many thanks
